
 -- QUESTION PAPER  ( 1.UMESH RATHOD )
----------------------------------------------------------------------------------------------------


--1 HOW TO SELECT UNIQUE RECORDS FROM A TABLE USING ANALYTICAL FUNCTION
SELECT * FROM (SELECT EID,CID,TYP_VEH ,ROW_NUMBER() OVER (PARTITION BY CID ORDER BY CID)AS GB FROM  SER_DET) 
  WHERE GB =1;


--2 How do you get the nth-highest salary for the employee table without a subquery on cid.
SELECT * FROM EMPLOYEE E1
WHERE  5= (SELECT DISTINCT COUNT(*) FROM EMPLOYEE E2 WHERE E1.ESAL <= E2.ESAL)


--3 WHAT IS THE RESULT OF NORMAL JOIN, LEFT OUTER JOIN, RIGHT OUTER JOIN AND FULL OUTER JOIN 
   --BETWEEN THE TABLE A & B AND QUERY ?
CREATE TABLE AA
(
COL_A        VARCHAR2(50)
);    

SELECT * FROM AA

INSERT INTO AA VALUES (1);
INSERT INTO AA VALUES (1);
INSERT INTO AA VALUES (0);
INSERT INTO AA VALUES ('NULL');


CREATE TABLE BB
(
COL_B        VARCHAR2(50)
);

SELECT * FROM BB

INSERT INTO BB VALUES (1);
INSERT INTO BB VALUES (0);
INSERT INTO BB VALUES ('NULL');
INSERT INTO BB VALUES ('NULL');

--NORMAL JOIN 
SELECT * FROM AA
 JOIN BB
ON COL_A = COL_B

--LEFT JOIN 
SELECT * FROM AA
LEFT JOIN BB
ON COL_A = COL_B

--RIGHT JOIN 
SELECT * FROM AA
RIGHT JOIN BB
ON COL_A = COL_B

--FULL JOIN 
SELECT * FROM AA
FULL JOIN BB
ON COL_A = COL_B


--4 SUPPOSE WE HAVE A CUSTOMER TABLE CONTAINIG THE FOLLOWING DATA.
    CUSTOMER_ID      CUSTOMER_NAME
    1               PRASHANT KAURAV
    2               ASHISH JHA
    3               ANKIT VARMA
    4               VINEET KUMAR
    5               RAHUL KUMAR
    
    OUTPUT--PRASHANT KAURAV;ASHISH JHA;ANKIT VARMA;VINEET KUMAR;RAHUL KUMAR

SELECT CUSTOMER_ID ||';'|| CUSTOMER_NAME FROM TABLE_NAME  -- TO CREATE TABLE THEN RUN THIS QUERY
SELECT * FROM TABLE_NAME

SELECT 'PRASHANT KAURAV'||';'||'ASHISH JHA'||';'||'ANKIT VARMA'||';'||'VINEET KUMAR'||';'||'RAHUL KUMAR' AS CUSTOMER_TABLE FROM DUAL;

--5 WRITE A SINGLE QUERY TO CALCULATE THE SUM OF ALL POSITIVE VALUES OF X AND THE SUM OF ALL NEGATIVE VALUES OF: (COL x: 2,-2,4,-4,-3,0,2)
CREATE TABLE T1
(
COLX NUMBER
);

SELECT * FROM T1

INSERT INTO T1 VALUES (2);
INSERT INTO T1 VALUES (-2);
INSERT INTO T1 VALUES (4);
INSERT INTO T1 VALUES (-4);
INSERT INTO T1 VALUES (-3);
INSERT INTO T1 VALUES (0);
INSERT INTO T1 VALUES (2);


SELECT SUM(CASE WHEN COLX >0 THEN COLX ELSE 0 END)AS POSITIVE_VALUES,
       SUM(CASE WHEN COLX <0 THEN COLX ELSE 0 END) AS NEGATIVE_VALUES FROM T1


--6 GIVEN TABLE:
          WEIGHT
          5.67
          34.567
          365.253
          34
          
    OUTPUT
    WEIGHT           KG      GMS
    5.67             5       67
    34.567           34      567
    365.253          365     235
    34               34      0





--7 HOW DO YOU COPY DATA FROM ONE TABLE TO ANOTHER TABLE 

CREATE TABLE PQR AS SELECT * FROM SER_DET;  	       
SELECT * FROM PQR                       ----COPY DATA

CREATE TABLE PQR1 AS SELECT * FROM SER_DET WHERE 1=0;
SELECT * FROM PQR1                 	    ---- ONLY SCHEMA COPY

CREATE TABLE PQR2 AS SELECT CID,EID FROM SER_DET;
SELECT * FROM PQR2                       -----ONLY 2 COLUMN SCHEMA COPY WITH DATA

CREATE TABLE PQR3 AS SELECT CID,EID FROM SER_DET WHERE 1=0;
SELECT * FROM PQR3                       ---- ONLY 2 COLUMN SCHEMA COPY






----8 HOW DO YOU GET THE LAST ID WITHOUT THE MAX FUNCTION 

SELECT * FROM (SELECT * FROM SER_DET ORDER BY ROWNUM DESC) WHERE ROWNUM<2
 
SELECT *  FROM SER_DET 


---9 GIVEN A TABLE EMPLOYEE HAVING COLUMN EMPLOYEE_NAME,AND EMPLOYEE_ID, WHAT WILL BE
-- THE RESULT OF THE SQL QUERY BELOW (SELECT EMPLYEE_NAME FROM EMPLOYEE ORDER BY 2 DESC)
SELECT FIRST_NAME,EMPLOYEE_ID FROM  HR.EMPLOYEES
ORDER BY 2 DESC;
(--2 = MEANS EMPLOYEE_ID)

---12 HOW CAN  YOU SELECT ALL THE  EVEN NUMBER RECORD FROM A TABLE ? ALL THE ODD NUMBER RECORDS
SELECT * FROM HR.EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=0;   --EVEN

SELECT * FROM HR.EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=1;   --ODD

--13---ASSUM A SCHEMA OF EMP (SELECT * FROM EMP,DEPT) 
SELECT * FROM EMP,EMP1


---14-- WRITE A SQL QUERY TO FIND 10TH HIGHEST SALARY FROM EMPLOYEES
SELECT * FROM HR.EMPLOYEES E1
WHERE 10= (SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES E2 WHERE E1.SALARY<=E2.SALARY)

SELECT * FROM HR.EMPLOYEES E1
WHERE 10=(SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES E2 WHERE E1.SALARY<=E2.SALARY)

----19-- HOW CAN YOU SELECT ALL THE EVEN NUMBER RECORDS FROM A TABLE ? ALL THE ODD NOS
SELECT * FROM HR.EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=0;     --EVEN EMPLOYEE_ID

SELECT * FROM HR.EMPLOYEES
WHERE MOD (EMPLOYEE_ID,2)=1;    	--ODD EMPLOYEE_ID


--20--WHAT IS THE DIFFERENCE BETWEEN THE WHERE AND HAVING CLAUSES ?


-----------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 
 -- QUESTION PAPER  ( 2.Amruta Shinde )
----------------------------------------------------------------------------------------------------

--1 ADD '***' BEFORE AND AFTER STRING 
SELECT LPAD('STRING',LENGTH('STRING')+3,'*'),
       RPAD('STRING',LENGTH('STRING')+3,'*') FROM DUAL

--2 EXTRACT THE @gmail.com FROM EMAIL ID- brainworks@gmail.com 
SELECT SUBSTR ('brainworks@gmail.com',-10,10) from dual

select substr ('brainworks@gmail.com',11,20) from dual


--3 INPUT-BRAINWORK (OUTPUT-COLUMN WISE)
SELECT SUBSTR('BRAINWORK',LEVEL,1) FROM DUAL
CONNECT BY LEVEL <= LENGTH('BRAINWORK')

--4. OUTPUT 
   *
   **
   ***
   
SELECT SUBSTR('***',1,LEVEL) FROM DUAL
CONNECT BY LEVEL<=3


--5 HOW TO CREATE THE NEW TABLE WITH SAME STRUCTURE WITH DATA OF EMPLOYEE TABLE

SELECT NEW_TABLE AS SELECT * FROM OLD_TABLE_NAME WHERE 1=0;


 -- 6.how to get 1 to 100 using sql query 
SELECT LEVEL FROM DUAL 
CONNECT BY LEVEL <=100


--7 DELETE DUPLICATE ROWS FROM EMPLOYEE TABLE 
DELETE FROM HR.EMPLOYEES
WHERE ROWID NOT IN
(SELECT MIN(ROWID) FROM HR.EMPLOYEES GROUP BY EMPLOYEE_ID)

--8 FIND THE ALL DETAILS OF EMPLOYEE WHO IS GETTING HIGHEST SALARY DEPARTMENT WISE 
SELECT * FROM HR.EMPLOYEES
WHERE SALARY IN
(SELECT MAX(SALARY) FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID)

-- 4TH HIGHEST SALARY
SELECT * FROM HR.EMPLOYEES E1
WHERE 4= (SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES E2 WHERE E1.SALARY<=E2.SALARY)


-- 2ND HIGHEST SALARY 
 SELECT * FROM HR.EMPLOYEES 
 WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES 
 WHERE SALARY <> (SELECT MAX(SALARY ) FROM HR.EMPLOYEES))


--  9. GET THE ALL DETAILS OF TOP 3 EMPLOYEES IN EACH DEPARTMENT EARNING MAX SALARY 
SELECT E.* FROM 
(SELECT DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY MAX(SALARY) DESC)AS RANK,
MAX(SALARY) AS MAX_SAL, FIRST_NAME , LAST_NAME , DEPARTMENT_ID ,JOB_ID , MANAGER_ID  FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID, FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID) E
WHERE RANK<=3
ORDER BY DEPARTMENT_ID ASC

         --OR--
SELECT * FROM
(SELECT E.*, ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC)AS RANK FROM HR.EMPLOYEES E)
WHERE RANK <=3


-- 10. FIND ALL DETAILS OF EMPLOYEES WHO IS EARNING SALARY GRETER THAN AVERAGE SALARY OF EMPLOYEE
SELECT * FROM HR.EMPLOYEES 
WHERE SALARY > 
(SELECT AVG(SALARY) FROM HR.EMPLOYEES)

--11. FIND THE LAST RECORD FROM EMPLOYEE TABLE 
SELECT * FROM EMPLOYEE
WHERE ROWID = (SELECT MAX(ROWID) FROM EMPLOYEE)

--12. DISPLAY FIRST 50% RECORDS FROM EMPLOYEEE TABLE

SELECT * FROM EMPLOYEE
WHERE ROWNUM <= (SELECT ROUND(COUNT(*)/2) FROM EMPLOYEE)
        --OR--
SELECT * FROM EMPLOYEE
WHERE ROWNUM <= (SELECT ROUND(COUNT(ROWNUM)/2) FROM EMPLOYEE)

-- 13. WHAT IS THE OUTPUT OF BELOW 
 /* SELECT 1 FROM DUAL 
    UNION 
    SELECT '1' FROM DUAL */

# THE OUTPUT OF THE ABOVE QUERY WILL BE 1 



-- 14. SELECT COUNT(NULL) FROM  HR. EMPLOYEES 

# THE OOUTPUT OF THE  ABOVE QUERY WILL BE  0

--  15 .INPUT (NOT SOLVED )
CREATE TABLE CCC(
COL1 VARCHAR2(10),
COL2 VARCHAR2(10),
COL3 VARCHAR2(10)
); 
SELECT * FROM CCC
INSERT INTO CCC VALUES ( 'A' , NULL , NULL );
INSERT INTO CCC VALUES ( NULL , 'B' , NULL );
INSERT INTO CCC VALUES ( NULL , NULL , 'C' );

 

SELECT COALESCE('A','NULL','NULL') AS CL1,
COALESCE ('NULL','B','NULL') AS CL2,
COALESCE ('NULL','NULL','C')AS CL3 FROM CCC


SELECT COALESCE(COL1,COL2,COL3) FROM CCC


-- 16 WHAT IS THE OUTPUT OF BELOW 
SELECT 1 + '1' FROM DUAL 
   
==> OUTPUT 2

-- 17.SPLIT THE NAME 'TEAM BRAIN WORKS ' INTO THREE DIFFERENT COLUMN 

SELECT SUBSTR('TEAM',INSTR('TEAM','T'),LENGTH('TEAM')) AS PART1,
 SUBSTR('BRAIN',INSTR('BRAIN','B'),LENGTH('BRAIN')) AS PART2,
 SUBSTR('WORKS',INSTR('WORKS','W'),LENGTH('WORKS')) AS PART3 FROM DUAL
                    --OR--
SELECT SUBSTR ('TEAM BRAIN WORKS' , 1,4) AS PART1,
       SUBSTR ('TEAM BRAIN WORKS',6,5 )AS PART2,
       SUBSTR ('TEAM BRAIN WORKS' ,11,6)AS PART3 
       FROM DUAL

-- 18.HOW TO DELETE NTH RECORD FROM GIVEN TABLE 
--EXAMPLE = DELETE 4TH RECORD FROM EMPLOYEES
SELECT * FROM 
(SELECT * FROM HR.EMPLOYEES
ORDER BY ROWNUM DESC)
WHERE ROWNUM <=5


--19. HOW TO DISPLAY EVEN ROWS FROM EMPLOYEE TABLE 

SELECT * FROM HR.EMPLOYEES
WHERE MOD (EMPLOYEE_ID,2)=0


-- 20. WRITE A QUERY TO FIND THE AGE OF THE PERSON IN YEAR , MONTH AND DAYS (CONSIDER THE PERSON DOB 25 FEB 1992)

SELECT TRUNC(MONTHS_BETWEEN (SYSDATE,'25-FEB-1992')/12)AS YEAR,
       TRUNC((MONTHS_BETWEEN (SYSDATE,'25-FEB-1992')/12 - TRUNC(MONTHS_BETWEEN (SYSDATE,'25-FEB-1992')/12))*12) AS MONTH,
       TRUNC(MOD((MONTHS_BETWEEN (SYSDATE,'25-FEB-1992')/12) *12,1)* 30)AS DAYS FROM DUAL;



-- 12-DEC-2003
SELECT  TRUNC (MONTHS_BETWEEN (SYSDATE ,' 12-DEC-2003')/12 )AS YEARS ,
TRUNC ((MONTHS_BETWEEN (SYSDATE ,' 12-DEC-2003')/12 - TRUNC (MONTHS_BETWEEN (SYSDATE ,' 12-DEC-2003')/12 )) * 12) AS MONTHS ,  
 TRUNC (MOD ((MONTHS_BETWEEN (SYSDATE ,' 12-DEC-2003')/12 ) *12 , 1) * 30) AS DAYS    
FROM DUAL

-- 09-FEB-1997
SELECT  TRUNC (MONTHS_BETWEEN (SYSDATE ,'09-FEB-1997')/12 )AS YEARS ,
TRUNC ((MONTHS_BETWEEN (SYSDATE ,' 09-FEB-1997')/12 - TRUNC (MONTHS_BETWEEN (SYSDATE ,' 09-FEB-1997')/12 )) * 12) AS MONTHS ,  
 TRUNC (MOD ((MONTHS_BETWEEN (SYSDATE ,' 09-FEB-1997')/12 ) *12 , 1) * 30) AS DAYS    
FROM DUAL

-----------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 
 -- QUESTION PAPER 3 ( 3.DHIRAJ SHINDE )
----------------------------------------------------------------------------------------------------



-- 1. REMOVE DUPLICATE RECORD FROM FOLLOWING TABLE

DELETE FROM ABC
WHERE ROWID NOT IN (SELECT MIN(ROWID)FROM ABC GROUP BY ID)

--2. WRITE DOWN SYNTAX FOR UPDATE STATEMENT
UPDATE EMPLOYEE
SET COLUMN_NAME='CONDITION'
WHERE ID=UPDATE_VALUE


--3. WRITE A QUERY FOR INNER , LEFT , RIGHT , FULL , OUTER JOIN FOR FOLLOWING TABLE 

CREATE TABLE STAFF_TABLE (
ID NUMBER ,
STAFF_NAME  VARCHAR2(40),
STAFF_AGE   VARCHAR2(40),
STAFF_ADD   VARCHAR2(10),
MONTHLY_PACKAGE VARCHAR2(20)

);


INSERT INTO STAFF_TABLE VALUES ( 1, 'ARYAN',22,'MUMBAI',18000);
INSERT INTO STAFF_TABLE VALUES (2,'SUSHIL' ,32,'DELHI',20000);
INSERT INTO STAFF_TABLE VALUES (3,'MONTY',25,'MOHALI',22000);
INSERT INTO STAFF_TABLE VALUES (4 ,'AMIT',20,'ALLAHBAD',12000);


CREATE TABLE PAYMENT_TABLE 
(
PAYMENT_ID    NUMBER ,
DATE_         DATE ,
STAFF_ID     NUMBER ,
AMOUNT NUMBER 
);

SELECT * FROM PAYMENT_TABLE 
INSERT INTO PAYMENT_TABLE VALUES (101,TO_DATE ('30-DEC-2009','DD-MM-YYYY') , 1,3000 )
INSERT INTO PAYMENT_TABLE VALUES (102,TO_DATE ('22-FEB-2010','DD-MM-YYYY') , 3,2500 );
INSERT INTO PAYMENT_TABLE VALUES (103,TO_DATE ('23-FEB-2010','DD-MM-YYYY') , 4,3500 );


-- FULL JOIN 

SELECT * FROM STAFF_TABLE S
JOIN PAYMENT_TABLE P
ON P.STAFF_ID = S.ID 

-- INNER JOIN 

SELECT * FROM STAFF_TABLE S
 INNER JOIN PAYMENT_TABLE P
ON P.STAFF_ID = S.ID 


-- LEFT JOIN 

SELECT * FROM STAFF_TABLE S
LEFT JOIN PAYMENT_TABLE P
ON P.STAFF_ID = S.ID 

-- RIGHT JOIN 
SELECT * FROM STAFF_TABLE S
RIGHT  JOIN PAYMENT_TABLE P
ON P.STAFF_ID = S.ID 

 -- CARTITIAN JOIN 
 SELECT * FROM STAFF_TABLE S
CROSS  JOIN PAYMENT_TABLE P 


--5 GET NUMBER OF DAYS LEFT IN CURRENT MONTH
SELECT MONTHS_BETWEEN('01-OCT-2023',SYSDATE)*31 FROM DUAL


--6 WRITE QUERY TO FIND 3rd HIGHEST SALARY
SELECT * FROM HR.EMPLOYEES E1
WHERE 3-1=(SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES E2 WHERE E2.SALARY > E1.SALARY)


-- 7 GET NO OF SECOND LEFT TODAY

SELECT (TRUNC(SYSDATE + 1) - SYSDATE) * 86400 AS seconds_left_today FROM DUAL;

--8. INPUT:-"BRAIN"
                      --OUTPUT:- ITS SHOW COLUMN WISE
SELECT SUBSTR('BRAIN',LEVEL,1) FROM DUAL
CONNECT BY LEVEL <= LENGTH('BRAIN')


--9. WHAT WILL BE OUTPUT OF "select abc 'null'" FROM DUAL
SELECT ABC 'NULL' FROM DUAL
 

-- 10. SELECT ROUOND(DECODE(.10*.10 + .10*+.10),0,1( .10*.10 + .10*.10)),1) 
SELECT ROUND(DECODE((.10*.10 + .10*+.10),0,1,( .10*.10 + .10*.10)),1) FROM DUAL
 
==> THE OUTPUT WILL BE ZERO 

SELECT ROUND(SUM(DECODE((1.10*1.10 + 1.10*1.10),0,2,( 1.10*1.10 + 1.10*1.10))),1) FROM DUAL


-- 11. WRITE A QUERY TO CHEAK COLUMN EXIST IN THE TABLE ? 
 SELECT * FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME = 'EMPLOYEES'

-- 12 CONVERT NUMBER 1352 INTO WORDS (ONE HUNDRED THREE HUNDRED FIFTY THREE 
SELECT TO_CHAR(TO_DATE(1352, 'J'), 'JSP') FROM DUAL;


--13. FIND ALL THE EMPLOYEES WHOSE NAMES ARE UPTO 15 CHARACTER LONG AND HAVE LATER r AT 3rd 
    --CHARACTER OF THE NAME. (WRITE QUERY-USE FRIST_NAME COLUMN)

SELECT FIRST_NAME FROM HR.EMPLOYEES
WHERE LENGTH(FIRST_NAME) <=15 AND FIRST_NAME LIKE('__r%')

                  --OR--
SELECT FIRST_NAME FROM HR.EMPLOYEES 
WHERE LENGTH(FIRST_NAME) <=15 AND SUBSTR(FIRST_NAME,3,1)='r'; 


-- 17. WRITE A SYNTAX TO THE WINDOW FUNCTION (RANK , DENSE_RANK , ROWNUMBER)

------------ RANK () -----------------------


SELECT FIRST_NAME , LAST_NAME , SALARY ,DEPARTMENT_ID , 
 RANK () OVER (PARTITION BY DEPARTMENT_ID  ORDER BY SALARY DESC)
 FROM HR.EMPLOYEES
 
-------------DENSE_RANK () ------------------
SELECT FIRST_NAME , LAST_NAME , SALARY ,DEPARTMENT_ID , 
DENSE_RANK () OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC)AS RANK 
FROM HR.EMPLOYEES

-----------ROWNUMBER------------
SELECT FIRST_NAME , LAST_NAME , SALARY ,DEPARTMENT_ID , 
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC)AS RANK 
FROM HR.EMPLOYEES

-- 18. WRITE A QUERY TO FETCH EVEN ROWS IN TABLE 
SELECT ROWNUM,E.* FROM HR.EMPLOYEES E
WHERE MOD(EMPLOYEE_ID,2)=0


-- 19. DISPLAY THE DEPARTMENT WHERE THE SUM OF SALARIES IS 50000 OR MORE 

SELECT SUM(SALARY),DEPARTMENT_ID FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>= 50000;




-----------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 
 -- QUESTION PAPER 4 ( 4.YOGESH KARADE )
----------------------------------------------------------------------------------------------------

--1.


--2.  


--3. s1=" python" , output="pythn" (Removing all vowels)

SELECT REGEXP_REPLACE('PYTHON', '[AEIOUaeiou]') AS RESULT FROM DUAL;


--4. S1 = 'PTYTHON' , OUTPT = O (REMOVING ALL CONSONENTS )
SELECT REGEXP_REPLACE('PYTHON', '[^ AEIOUaeiou]') AS RESULT FROM DUAL;

--5.


--6. output the query
SELECT LEVEL FROM DUAL
CONNECT BY LEVEL<=10


--7. OUTPUT OF 
     SELECT SUBSTR('ORACLE',6,LEVEL) FROM DUAL CONNECT BY LEVEL <= LENGTH('ORACLE')
     
==>  OUTPUT 
E
E
E
E
E
E


--8 OUTPUT OF THE QUERY 
SELECT SUBSTR ('ABCD',1,1) A,SUBSTR ('ABCD',2,1) B,
 SUBSTR ('ABCD',3,1)C, SUBSTR('ABCD',4,1)D FROM DUAL 
 CONNECT BY LEVEL <= LENGTH('ABCD')

-- OUTPUT 
A B C D -- COULUMN NAME 

A B C D -- ROWS
A B C D
A B C D 
A B C D  



--9. OUTPUT OF THE QUERY 
SELECT STR , COUNT (STR)FROM (
SELECT SUBSTR ('HELLOW',LEVEL,1)STR FROM DUAL
 CONNECT BY LEVEL <= LENGTH ('HELLOW'))
 GROUP BY STR 

STR      COUNT(STR)
H         1 
E         1
L         2 
O         1 
W         1 



-- 10 S1 = brainworks_team@gmail.com  , output = @gmail.com 
SELECT SUBSTR('brainworks_team@gmail.com', INSTR('brainworks_team@gmail.com','@'),LENGTH('@gmail.com')) from dual;

       --OR
SELECT SUBSTR('brainworks_team@gmail.com',16,10) FROM DUAL

       --OR
SELECT SUBSTR('brainworks_team@gmail.com',-10,10) FROM DUAL



-- 11. output the query    select 1+1+2+'5' from dual 

==> output  = 9 




-----------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 
 -- QUESTION PAPER 5 ( 5.HARSHADA )
----------------------------------------------------------------------------------------------------

--1. HOW TO SELECT UNIQUE RECORDS FROM A TABLE USING A SQL QUERY?
SELECT DISTINCT * FROM HR.EMPLOYEES

--2. HOW TO DELETE DUBLICATE RECORDS FROM A TABLE USING A SQL QUERY ?
DELETE FROM ABC
WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM ABC GROUP BY ROWID)

--3. WHAT IS THE RESULT OF NORMAL JOIN, LEFT OUTER JOIN, RIGHT OUTER JOIN, AND FULL OUTER JOIN BETWEEN THE TABLE A & B ?


--4. FIND SECOND MAX SALARY FROM EMPLOYEE
SELECT * FROM EMPLOYEE E1
WHERE 2= (SELECT COUNT(*) FROM EMPLOYEE E2 WHERE E1.ESAL<=E2.ESAL)

--5. WRITE A SYNTAX FRO VIEW?
SELECT * FROM EMPLOYEE

--6. GIVE EXAMPLE ON MERGE STATEMENT? 


--7. CAN WE RENAME A COLUMN IN THE OUTPUT OF THE SQL QUERY?
SELECT OLD_NAME AS NEW_NAME FROM TABLE_NAME

--8. SUPPOSE A STUDENT COLUMN HAS TWO COLUMN, NMAE AND MARKS.
     --HOW TO GET NMAES AND MARKS OF THE TOP THREE STUDENTS? 

SELECT * FROM (SELECT * FROM EMPLOYEE ORDER BY ESAL DESC) WHERE ROWNUM<=3


--9. HOW TO GET NAME AND MARKS OF THE TOP THREE STUDENT?
SELECT * FROM (SELECT * FROM EMPLOYEE ORDER BY ESAL DESC) WHERE ROWNUM<=3

--10. INPUT: NAME     --OUTPUT: COLUMN WISE NAME 
SELECT SUBSTR('NAME',LEVEL,1) FROM DUAL
CONNECT BY LEVEL<= LENGTH('NAME')

--11. HOW TO FETCH CURRENT DATE AND TIME?
SELECT SYSDATE FROM DUAL;

--12. 

--13.INPUT  A       NULL        NULL           --OUTPUT  A
             NULL    B           NULL                    B
             NULL    NULL        C                       C

 SELECT COALESCE(COL1,COL2,COL3) AS PQR FROM CCC


--14.  INPUT  A       NULL        NULL           
             NULL    B           NULL                    
             NULL    NULL        C                        

       --OUTPUT:  A B C

SELECT LISTAGG(COL1,', ') WITHIN GROUP (ORDER BY COL1) AS list FROM CCC GROUP BY COL1,
 LISTAGG(COL2,', ') WITHIN GROUP (ORDER BY COL2) AS list FROM CCC GROUP BY COL2,
 LISTAGG(COL3,', ') WITHIN GROUP (ORDER BY COL3) AS list FROM CCC GROUP BY COL3 FROM CCC


--15. GIVE EXAMPLE ON CASE WHEN ?
SELECT E.*, 
( CASE
  WHEN ESAL>=1500 THEN 'TOP_PAID'
  WHEN ESAL<=1100 THEN 'LOWEST_PAID'
    ELSE 'MEDIUM_PAID'
      END)AS PAID
      FROM EMPLOYEE E

--16 WRITE A SQL QUERY TO FIND EMPLOYEES WITH SAME SALARY

SELECT E1.EMPLOYEE_ID,E1.FIRST_NAME,E1.SALARY,E2.EMPLOYEE_ID,E2.FIRST_NAME,E2.SALARY FROM HR.EMPLOYEES E1
JOIN HR.EMPLOYEES E2
ON E1.SALARY=E2.SALARY
WHERE E1.EMPLOYEE_ID<>E2.EMPLOYEE_ID


--17. WRITE A SQL QUERY TO FETCH DEPARTMENTS ALONG WITH THE TOTAL SALARIES PAID FOR EACH OF THEM 

SELECT SUM(SALARY),DEPARTMENT_ID FROM HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID

--18. WRITE A SQL QUERY TO SHOW ALL DEPARTMENTS ALONG WITH THE NUMBER OF PEPOLE WORKING THERE
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID

--19 WRITE A SQL QUERY TO PRINT DETAILS OF  EMPLOYEE 'Jennifer' AND 'James'

SELECT * FROM HR.EMPLOYEES
WHERE FIRST_NAME IN ('Jennifer','James')


--20. WRITE A SQL QUERY TO FIND ONLY ODD ROWS FROM EMPLOYEE TABLE?
SELECT * FROM HR.EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=1

--21. WRITE A SQL QUERY TO FIND ALL EMPLOYEES WHO HAVE BONUS RECORD IN BONUS TABLE?
SELECT * FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL

----------------------------------------------------------------------------------------------------
 -- QUESTION PAPER 6 ( 6.VAIBHAV SONTAKE )
----------------------------------------------------------------------------------------------------

--1. FIND THE MAXIMUM SALARY ALL POSSIBLE WAYS 
SELECT * FROM HR.EMPLOYEES
WHERE SALARY= (SELECT MAX(SALARY) FROM HR.EMPLOYEES)


SELECT * FROM (SELECT E.*, ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS OS FROM HR.EMPLOYEES E)
WHERE OS=1


--2. FIND NTH MAXIMUM SALARY IN ALL POSSIBLE WAYS
SELECT * FROM HR.EMPLOYEES E1
WHERE 10=
(SELECT COUNT(DISTINCT SALARY) FROM HR.EMPLOYEES E2
WHERE E2.SALARY > E1.SALARY)


--3. FIND NTH MAXIMUM SALARY DEPARTMENT WISE IN ALL THE POSSIBLE WAYS   

SELECT MAX(SALARY),JOB_ID FROM HR.EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID,MAX(SALARY) OVER (PARTITION BY JOB_ID ORDER BY JOB_ID DESC) FROM HR.EMPLOYEES


--4 HOW TO FETCH N RECORDS IN ALL POSSIBLE WAYS ? CONSIDER N = 10
SELECT * FROM
(SELECT E.*, ROW_NUMBER() OVER(ORDER BY EMPLOYEE_ID) AS AA FROM HR.EMPLOYEES E) 
WHERE AA=1;


--5 FIND RECORD IN RANGE OF 10-20?
SELECT * FROM
(SELECT E.*, ROW_NUMBER() OVER(ORDER BY EMPLOYEE_ID) AS AA FROM HR.EMPLOYEES E) 
WHERE AA BETWEEN 10 AND 20;

--6 FIND EXACT MIDDLE RECORD FROM TABLE?
SELECT * FROM HR.EMPLOYEES
WHERE ROWNUM<=(SELECT ROUND (COUNT(*)/2) FROM HR.EMPLOYEES)
MINUS
SELECT* FROM HR.EMPLOYEES
WHERE ROWNU  WM != (SELECT ROUND(COUNT(*)/2) FROM HR.EMPLOYEES)

--7 GET FIRST 50% RECORD FROM TABLE.
SELECT * FROM HR.EMPLOYEES
WHERE ROWNUM<=(SELECT ROUND(COUNT(*)/2) FROM HR.EMPLOYEES)

--8 FIND THE LAST DAY OF YEAR
SELECT SYSDATE FROM DUAL
WHERE LAST_DAY=SYSDATE

























